variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    MYSQL_ROOT_PASSWORD: app
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/development/public

stages:
    - Static validation
    - Testing

default:
    image: shopware/development:latest
    before_script:
        - zip -rq plugin.zip .
        - git clone --branch master http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/development.git
        - rm -rf development/platform
        - git clone --branch master http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git development/platform
        - unzip -q plugin.zip -d development/custom/plugins/SwagMigrationAssistant
        - cd development
        - cp -v dev-ops/gitlab/.psh.yaml.override .
        - /entrypoint supervisord > /dev/null 2>&1 &


# Stage: Static validation
PHP analyze:
    stage: Static validation
    services:
        - name: mysql:5.7
          alias: mysql
    script:
        - ./psh.phar init
        - php bin/console plugin:install --activate SwagMigrationAssistant
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagMigrationAssistant
        - php ../../../dev-ops/analyze/vendor/bin/ecs check --config=../../../vendor/shopware/platform/easy-coding-standard.php bin Command Controller Core DependencyInjection Exception Migration Profile Resources Test SwagMigrationAssistant.php
        - php ../../../dev-ops/analyze/vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v
        - bin/static-analyze.sh

ToDos resolved:
    stage: Static validation
    allow_failure: true
    script:
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagMigrationAssistant
        - bin/check-todos.sh $CI_COMMIT_BRANCH

PHPUnit (MariaDB):
    stage: Testing
    services:
        -   name: mariadb:10.3
            alias: mysql
    script:
        - apt-get update && apt-get --assume-yes install mysql-client
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagMigrationAssistant/Test
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/services/testdata.git testData
        - cd -
        - mysql -uroot -p"$MYSQL_ROOT_PASSWORD" --host mysql < $CI_PROJECT_DIR/development/custom/plugins/SwagMigrationAssistant/Test/testData/Migration/sw55.sql
        - ./psh.phar init
        - php bin/console plugin:install --activate SwagMigrationAssistant
        - composer dump-autoload -d custom/plugins/SwagMigrationAssistant
        - ./psh.phar init-test-databases
        - php -d pcov.enabled=1 -d pcov.directory=$CI_PROJECT_DIR
            vendor/bin/phpunit
            --configuration custom/plugins/SwagMigrationAssistant/phpunit.xml.dist
            --log-junit build/artifacts/phpunit.junit.xml
            --colors=never
            --coverage-clover build/artifacts/phpunit.clover.xml
            --coverage-html build/artifacts/phpunit-coverage-html
            --coverage-text
    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    artifacts:
        paths:
            - development/build/artifacts/phpunit.clover.xml
        reports:
            junit: development/build/artifacts/phpunit.junit.xml
